defaultProxyProvider: default
docker:
    local:
        host: unix:///var/run/docker.sock
        targetHostname: 192.168.86.165 #host.docker.internal #192.168.86.165
        tryDockerInternalNetwork: false
lists: {}
tailscale:
    providers:
        default:
            authKey: "tskey-auth-kVduVeSwnf11CNTRL-mTmyLFyNTc6UvkXNK3ppc6upkG9S8CEi"
            controlUrl: https://controlplane.tailscale.com
    dataDir: /data/
http:
    hostname: 0.0.0.0
    port: 8080
log:
    level: info
    json: false
proxyAccessLog: true