# =============================================================================
# UPTIME KUMA - SERVICE MONITORING & STATUS PAGES
# =============================================================================
# Beautiful monitoring dashboard for all services
# Provides uptime monitoring, alerting, and status pages
# =============================================================================

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped

    ports:
      - 3001:3001
    
    volumes:
      # Monitoring data, configuration, alerts
      - homelab_infra_kuma_data:/app/data
    
    environment:
      - TZ=${TZ:-UTC}
    
    networks:
      - homelab_network
    
    labels:
      # Enable Tailscale access
      tsdproxy.enable: "true"
      tsdproxy.name: "kuma"

    # Uptime Kuma health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Uptime Kuma takes a bit longer to start